// library/packages/vue/src/greet.vue
<template>
  <div>
    <input
      placeholder="Your name"
      :value="name"
      @change="name = $event.target.value"
    />
    <div>Hello, {{ name }}!</div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "greet",

  data() {
    return { name: "" };
  },
});
</script>

// library/packages/react-native/src/greet.tsx
import * as React from "react";
import {
  FlatList,
  ScrollView,
  View,
  StyleSheet,
  Image,
  Text,
  Pressable,
} from "react-native";
import { useState } from "react";

function Greet(props: any) {
  const [name, setName] = useState(() => "");

  return (
    <View>
      <View
        placeholder="Your name"
        value={name}
        onChange={(e) => setName(e.target.value)}
      />
      <View>
        <Text>Hello, </Text>
        <Text>{name}</Text>
        <Text>!</Text>
      </View>
    </View>
  );
}

export default Greet;
